# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  
  codecoolseriesangularbackend:
    image: codecoolseriesangularbackend
    build:
      context: ../
      dockerfile: './Dockerfile'
    ports:
      - 7206:7206
    
    networks:
      - database

  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_DB: 'codecool-series'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
      ports:
        - '5432:5432'
      volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./data/01_create_schema.sql:/docker-entrypoint-initdb.d/01_create_schema.sql
          - ./data/codecool_public_genres.sql:/docker-entrypoint-initdb.d/codecool_public_genres.sql
          - ./data/codecool_public_shows.sql:/docker-entrypoint-initdb.d/codecool_public_shows.sql
          - ./data/codecool_public_show_genres.sql:/docker-entrypoint-initdb.d/codecool_public_show_genres.sql
          - ./data/codecool_public_seasons.sql:/docker-entrypoint-initdb.d/codecool_public_seasons.sql
          - ./data/codecool_public_episodes.sql:/docker-entrypoint-initdb.d/0codecool_public_episodes.sql
          - ./data/codecool_public_actors.sql:/docker-entrypoint-initdb.d/codecool_public_actors.sql
          - ./data/codecool_public_show_characters.sql:/docker-entrypoint-initdb.d/codecool_public_show_characters.sql

      networks:
        - database

  
networks:
  database:
    driver: bridge
