# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  codecoolseriesangularbackend:
    image: codecoolseriesangularbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7206:7206
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
